export const PRUDUCT_LIST_REQUEST = 'PRUDUCT_LIST_REQUEST';
export const PRUDUCT_LIST_SUCCESS = 'PRUDUCT_LIST_SUCCESS';
export const PRUDUCT_LIST_FAIL = 'PRUDUCT_LIST_FAIL';


export const PRUDUCT_DETAILS_REQUEST = 'PRUDUCT_DETAILS_REQUEST';
export const PRUDUCT_DETAILS_SUCCESS = 'PRUDUCT_DETAILS_SUCCESS';
export const PRUDUCT_DETAILS_FAIL = 'PRUDUCT_DETAILS_FAIL';